### ISSUE TITLE
Could not find node_modules directory in __dirname on install

### ISSUE THREAD

**Issue by 42iscool42** [janniks/basetag#10]
Hello, I am using node v12.18.3 and npm version 6.14.6 on Windows  When I try to install the package, I get the following message:
`basetag@1.0.0
- Could not find node_modules directory in __dirname
- Not creating $ symlink`

I'm not sure what seems to be causing this issue.  I tried remove the node_modules folder and re-running npm i but that didn't seem to fix the issue.  Any help would be greatly appreciated.

**Comment by GameMaster2030** [comment]
I'm pretty sure it doesn't work on Windows at all, it works fine on Linux. 
You can do it manually on Windows quite easily with this command: `mklink /j "node_modules\$" .`

**Comment by janniks** [comment]
We are working on a windows fix

**Comment by coolaj86** [comment]
Imagine my great surprise to find that, indeed, @GameMaster2030 is correct:

Windows junctions can be used **without super user privileges** for directories in Windows 10. This is great news!

```bash
mklink /j "node_modules\$" .
```

However, it cannot be used with the built-in `fs.symlink`. I believe that is due to non-junction symlinks requiring admin privileges.

```js
var fs = require('fs');
fs.mkdirSync("./node_modules", { recursive: true });
fs.symlinkSync("./node_modules/$", "../");
{
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM'
}
```

You've got to shell out:

```js
var exec = require('child_process').exec;
exec('mklink /j ".\\node_modules\\$" ".\"', function (err, stdout, stderr) {
  // ...
})
```

Note that the target is relative to the ***working directory*** rather than the *nix way of having it relative to the link.

**Comment by janniks** [comment]
👋🏻 version `1.1.0` is live and supports Windows. Feel free to let me know if there are still any issues.
